variables:
  DOCKER_IMAGE_DOCKER: docker:stable-dind
  NAME_LATEST_TAG: latest
  NAME_DEVELOP_TAG: develop

image: $DOCKER_IMAGE_DOCKER

stages:
  - build
  - tag-develop
  - tag-master
  - deploy-develop
  - deploy-master

services:
  - docker:dind

before_script:
  # $CI_JOB_TOKEN, a special token provided by GitLab
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

# Build image for every commit
Build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:$NAME_LATEST_TAG || true
    # The built image is tagged locally with the commit SHA
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --cache-from $CI_REGISTRY_IMAGE:$NAME_LATEST_TAG
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

Tag develop:
  stage: tag-develop
  variables:
    GIT_STRATEGY: fetch
  only:
    - develop
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # Tag it "develop"
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$NAME_DEVELOP_TAG
    - docker push $CI_REGISTRY_IMAGE:$NAME_DEVELOP_TAG

Tag master:
  stage: tag-master
  variables:
    # Again, we do not need the source code here. Just playing with Docker.
    GIT_STRATEGY: fetch
  only:
    - tags
    - master
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # Tag it with the latest tag
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    # Tag it latest for the latest master commit
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$NAME_LATEST_TAG
    - docker push $CI_REGISTRY_IMAGE:$NAME_LATEST_TAG

Deploy develop:
  stage: deploy-develop
  only:
    - develop
  script:
    - echo "Hello from develop deployment"

Deploy master:
  stage: deploy-master
  only:
    - master
  script:
    - echo "Hello from master deployment"
