variables:
  DOCKER_IMAGE_DOCKER: docker:stable-dind
  SONARQUBE_HOST: https://se1-sonarqube.dev.ifs.hsr.ch
  NAME_LATEST_TAG: latest
  NAME_DEVELOP_TAG: develop

image: $DOCKER_IMAGE_DOCKER

stages:
  - build
  - sonarqube-build
  - sonarqube-check
  - lint
  - tag-develop
  - tag-master
  - deploy-develop
  - deploy-master

services:
  - docker:dind


# Build image for every commit
Build:
  stage: build
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$NAME_DEVELOP_TAG || true
    # The built image is tagged locally with the commit SHA
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --cache-from $CI_REGISTRY_IMAGE:$NAME_DEVELOP_TAG
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA


Sonarqube-Build:
   stage: sonarqube-build
   script: 
      - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
      - docker pull $CI_REGISTRY_IMAGE:$NAME_DEVELOP_TAG || true
      # The built image is tagged locally with the commit SHA
      - >
        docker build
        --pull
        --file Dockerfile.dev
        --build-arg VCS_REF=$CI_COMMIT_SHA
        --build-arg VCS_URL=$CI_PROJECT_URL
        --cache-from $CI_REGISTRY_IMAGE:$NAME_DEVELOP_TAG
        --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}_Dev_Build
        .
      - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}_Dev_Build
   only: ['merge_requests', 'develop', 'master']


Sonarqube:
  stage: sonarqube-check
  image:
    name: sonarsource/sonar-scanner-cli:4.6
    entrypoint: [""]
  variables:
    # Defines the location of the analysis task cache
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    # Tells git to fetch all the branches of the project, required by the analysis task
    GIT_DEPTH: "0"
  allow_failure: true
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.host.url="${SONARQUBE_HOST}" -Dsonar.login="${SONARQUBE_TOKEN}"
  only: ['merge_requests', 'develop', 'master']


Linting:
  stage: lint
  only: ['merge_requests', 'develop', 'master']
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    entrypoint: [""]
  script:
    - apk --update add nodejs npm
    - npm run lint


Tag develop:
  stage: tag-develop
  variables:
    GIT_STRATEGY: none
  only:
    - develop
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # Tag it "develop"
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$NAME_DEVELOP_TAG
    - docker push $CI_REGISTRY_IMAGE:$NAME_DEVELOP_TAG

Tag master:
  stage: tag-master
  variables:
    # Again, we do not need the source code here. Just playing with Docker.
    GIT_STRATEGY: none
  only:
    - tags
    - master
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # Tag it with the latest tag
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    # Tag it latest for the latest master commit
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$NAME_LATEST_TAG
    - docker push $CI_REGISTRY_IMAGE:$NAME_LATEST_TAG

# TODO implement
Deploy develop:
  stage: deploy-develop
  only:
    - develop
  script:
    - echo "Hello from develop deployment"

# TODO implement
Deploy master:
  stage: deploy-master
  only:
    - master
  script:
    - echo "Hello from master deployment"
