# build environment
FROM node:14.16-alpine AS build

WORKDIR /app

COPY . .
RUN mv .env-prod .env

RUN npm install
RUN npm ci
RUN npm run build


# production environment
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
